In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_all = pd.read_csv('Tägliche Aktivitätswerte.csv')
df_all

,Datum,Anzahl der Aktivitätsminuten,Kalorien (kcal),Distanz (m),Kardiopunkte,Kardiominuten,Minimaler Breitengrad (Grad),Minimaler Längengrad (Grad),Maximaler Breitengrad (Grad),Maximaler Längengrad (Grad),...,Maximales Gewicht (kg),Minimales Gewicht (kg),Radfahren – Dauer (ms),Inaktiv – Dauer (ms),Gehen – Dauer (ms),Laufen – Dauer (ms),Seilspringen – Dauer (ms),Krafttraining – Dauer (ms),Intervalltraining – Dauer (ms),Gehen mit Schritttempovorgabe – Dauer (ms)
0,2021-01-08,NaN,391.232563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-09,NaN,1564.500015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-10,32.0,1667.712891,1283.078246,NaN,NaN,NaN,NaN,NaN,NaN,...,73.0,73.0,NaN,80788250.0,1750918.0,NaN,NaN,NaN,NaN,NaN
3,2021-01-11,20.0,1656.525290,786.421561,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,49764007.0,1561130.0,NaN,NaN,NaN,NaN,NaN
4,2021-01-12,28.0,1642.704709,959.737564,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1326675.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,2022-07-01,157.0,1797.368676,7316.024970,37.0,37.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5751984.0,NaN,NaN,NaN,NaN,NaN
238,2022-07-02,181.0,1876.325572,8411.493719,31.0,31.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7197797.0,NaN,NaN,NaN,NaN,NaN
239,2022-07-03,140.0,1786.201550,7194.493707,49.0,49.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5547492.0,NaN,NaN,NaN,NaN,NaN
240,2022-07-04,242.0,2020.381994,12128.564225,78.0,77.0,NaN,NaN,NaN,NaN,...,69.0,69.0,NaN,NaN,9805315.0,NaN,NaN,NaN,NaN,NaN
241,2022-07-05,35.0,629.162444,1258.859055,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,921373.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.p